### ISSUE TITLE
Using discord name for SRC name when name is not specified.

### ISSUE THREAD

**Issue by Em0nky** [Em0nky/PortalBot#20]
Using discord name for SRC name when name is not specified.
This allows users to more easily look at their own stuff by typing less.

Em0nky#3714 Using a command like "!pf" would then result in doing "!pf Em0nky"
Em0nky#3714 Using a command like "!recent" would then result in doing "!recent Em0nky"
Em0nky#3714 Using a command like "!run oob 14" would then result in doing "!run Em0nky oob 14"

**Comment by lundylizard** [comment]
Linking your speedrun.com profile will be added in #36
