### ISSUE TITLE
Pages for Leaderboard, Levelboard, and Profile Commands

### ISSUE THREAD

**Issue by Em0nky** [Em0nky/PortalBot#3]
Allowing the bot to display the next or previous 10 runs based on reactions.
Alternatively, the newer integrated buttons would also be better as it would allow for quickly going to a specific page

**Comment by lundylizard** [comment]
I'm adding sort options to #36, not sure if that makes this obsolete. I think when people wanna look for a specific rank they can / will be using the !run or !leaderboard command
